/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CalcoloPrestito {
    'tipocanale': string;
    'tipoprestito': string;
  }
}

declare global {


  interface HTMLCalcoloPrestitoElement extends Components.CalcoloPrestito, HTMLStencilElement {}
  var HTMLCalcoloPrestitoElement: {
    prototype: HTMLCalcoloPrestitoElement;
    new (): HTMLCalcoloPrestitoElement;
  };
  interface HTMLElementTagNameMap {
    'calcolo-prestito': HTMLCalcoloPrestitoElement;
  }
}

declare namespace LocalJSX {
  interface CalcoloPrestito {
    'tipocanale'?: string;
    'tipoprestito'?: string;
  }

  interface IntrinsicElements {
    'calcolo-prestito': CalcoloPrestito;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'calcolo-prestito': LocalJSX.CalcoloPrestito & JSXBase.HTMLAttributes<HTMLCalcoloPrestitoElement>;
    }
  }
}


